orbs:
  codecov: codecov/codecov@3.2.4

version: 2.1

jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - codecov/upload:
          token: CODECOV_TOKEN
          file: coverage/lcov.info 
      - store_artifacts:
          path: ~/src/build

workflows:
  build-deploy:
    jobs:
      - build
